/*
 * types.ts
 *
 * Copyright (c) 2022, 2023 Xiongfei Shi
 *
 * Author: Xiongfei Shi <xiongfei.shi(a)icloud.com>
 * License: Apache-2.0
 *
 * https://github.com/shixiongfei/napi-ctp
 */

/** 消息事件回调接口 */
export type CallbackFunction = (message?: number | object) => void;

/** 行情消息事件 */
export type MarketDataEvent =
  | "quit"
  | "front-connected"
  | "front-disconnected"
  | "heart-beat-warning"
  | "rsp-user-login"
  | "rsp-user-logout"
  | "rsp-qry-multicast-instrument"
  | "rsp-error"
  | "rsp-sub-market-data"
  | "rsp-unsub-market-data"
  | "rsp-sub-for-quote"
  | "rsp-unsub-for-quote"
  | "rtn-depth-market-data"
  | "rtn-for-quote";

/** 交易消息事件 */
export type TraderEvent =
  | "quit"
  | "front-connected"
  | "front-disconnected"
  | "heart-beat-warning"
  | "rsp-authenticate"
  | "rsp-user-login"
  | "rsp-user-logout"
  | "rsp-user-password-update"
  | "rsp-trading-account-password-update"
  | "rsp-user-auth-method"
  | "rsp-gen-user-captcha"
  | "rsp-gen-user-text"
  | "rsp-order-insert"
  | "rsp-parked-order-insert"
  | "rsp-parked-order-action"
  | "rsp-order-action"
  | "rsp-qry-max-order-volume"
  | "rsp-settlement-info-confirm"
  | "rsp-remove-parked-order"
  | "rsp-remove-parked-order-action"
  | "rsp-exec-order-insert"
  | "rsp-exec-order-action"
  | "rsp-for-quote-insert"
  | "rsp-quote-insert"
  | "rsp-quote-action"
  | "rsp-batch-order-action"
  | "rsp-option-self-close-insert"
  | "rsp-option-self-close-action"
  | "rsp-comb-action-insert"
  | "rsp-qry-order"
  | "rsp-qry-trade"
  | "rsp-qry-investor-position"
  | "rsp-qry-trading-account"
  | "rsp-qry-investor"
  | "rsp-qry-trading-code"
  | "rsp-qry-instrument-margin-rate"
  | "rsp-qry-instrument-commission-rate"
  | "rsp-qry-exchange"
  | "rsp-qry-product"
  | "rsp-qry-instrument"
  | "rsp-qry-depth-market-data"
  | "rsp-qry-trader-offer"
  | "rsp-qry-settlement-info"
  | "rsp-qry-transfer-bank"
  | "rsp-qry-investor-position-detail"
  | "rsp-qry-notice"
  | "rsp-qry-settlement-info-confirm"
  | "rsp-qry-investor-position-combine-detail"
  | "rsp-qry-cfmmc-trading-account-key"
  | "rsp-qry-e-warrant-offset"
  | "rsp-qry-investor-product-group-margin"
  | "rsp-qry-exchange-margin-rate"
  | "rsp-qry-exchange-margin-rate-adjust"
  | "rsp-qry-exchange-rate"
  | "rsp-qry-sec-agent-acid-map"
  | "rsp-qry-product-exch-rate"
  | "rsp-qry-product-group"
  | "rsp-qry-mm-instrument-commission-rate"
  | "rsp-qry-mm-option-instr-comm-rate"
  | "rsp-qry-instrument-order-comm-rate"
  | "rsp-qry-sec-agent-trading-account"
  | "rsp-qry-sec-agent-check-mode"
  | "rsp-qry-sec-agent-trade-info"
  | "rsp-qry-option-instr-trade-cost"
  | "rsp-qry-option-instr-comm-rate"
  | "rsp-qry-exec-order"
  | "rsp-qry-for-quote"
  | "rsp-qry-quote"
  | "rsp-qry-option-self-close"
  | "rsp-qry-invest-unit"
  | "rsp-qry-comb-instrument-guard"
  | "rsp-qry-comb-action"
  | "rsp-qry-transfer-serial"
  | "rsp-qry-account-register"
  | "rsp-error"
  | "rtn-order"
  | "rtn-trade"
  | "err-rtn-order-insert"
  | "err-rtn-order-action"
  | "rtn-instrument-status"
  | "rtn-bulletin"
  | "rtn-trading-notice"
  | "rtn-error-conditional-order"
  | "rtn-exec-order"
  | "err-rtn-exec-order-insert"
  | "err-rtn-exec-order-action"
  | "err-rtn-for-quote-insert"
  | "rtn-quote"
  | "err-rtn-quote-insert"
  | "err-rtn-quote-action"
  | "rtn-for-quote"
  | "rtn-cfmmc-trading-account-token"
  | "err-rtn-batch-order-action"
  | "rtn-option-self-close"
  | "err-rtn-option-self-close-insert"
  | "err-rtn-option-self-close-action"
  | "rtn-comb-action"
  | "err-rtn-comb-action-insert"
  | "rsp-qry-contract-bank"
  | "rsp-qry-parked-order"
  | "rsp-qry-parked-order-action"
  | "rsp-qry-trading-notice"
  | "rsp-qry-broker-trading-params"
  | "rsp-qry-broker-trading-algos"
  | "rtn-from-bank-to-future-by-bank"
  | "rtn-from-future-to-bank-by-bank"
  | "rtn-repeal-from-bank-to-future-by-bank"
  | "rtn-repeal-from-future-to-bank-by-bank"
  | "rtn-from-bank-to-future-by-future"
  | "rtn-from-future-to-bank-by-future"
  | "rtn-repeal-from-bank-to-future-by-future-manual"
  | "rtn-repeal-from-future-to-bank-by-future-manual"
  | "rtn-query-bank-balance-by-future"
  | "err-rtn-bank-to-future-by-future"
  | "err-rtn-future-to-bank-by-future"
  | "err-rtn-repeal-bank-to-future-by-future-manual"
  | "err-rtn-repeal-future-to-bank-by-future-manual"
  | "err-rtn-query-bank-balance-by-future"
  | "rtn-repeal-from-bank-to-future-by-future"
  | "rtn-repeal-from-future-to-bank-by-future"
  | "rsp-from-bank-to-future-by-future"
  | "rsp-from-future-to-bank-by-future"
  | "rsp-query-bank-account-money-by-future"
  | "rtn-open-account-by-bank"
  | "rtn-cancel-account-by-bank"
  | "rtn-change-account-by-bank"
  | "rsp-qry-classified-instrument"
  | "rsp-qry-comb-promotion-param"
  | "rsp-qry-risk-settle-invst-position"
  | "rsp-qry-risk-settle-product-status";